### ISSUE TITLE
Reorder Effects from the 'Enabled' Area.

### ISSUE THREAD

**Issue by joshwahwalters** [pmeas/pmeas-frontend#15]
Dragging items in the 'Enabled' area should allow the user to rearrange the effects order

**Comment by joshwahwalters** [comment]
Along with this feature I will add another small feature that displays the enabled effect's 'X' delete button on mouse hover

**Comment by Druage** [comment]
I'll turn that into a new issue.

**Comment by Druage** [comment]
We found out that the order does not matter all. Pyo has it's own ordering.
